[package]
name = "wallpaper-cava"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wallpaper-cava"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
khronos-egl = { version = "6.0.0", features = [
    "static",
    "1_0",
    "1_1",
    "1_2",
    "1_3",
    "1_4",
    "1_5",
] }
serde = { version = "1.0.203", features = ["derive"] }
smithay-client-toolkit = "0.20.0"
toml = "0.8.14"
wayland-egl = "0.32.0"
